/* Configuración del curso y textos de interfaz en español. */
window.COURSE_CONFIG = {
  "id": "matematicas-9-mep",
  "name": "Matemáticas 9.º Año — MEP",
  "shortName": "Matemáticas 9.º",
  "description": "Práctica para la segunda convocatoria de Matemáticas de noveno año del MEP de Costa Rica.",
  "language": "es",
  "version": "1.0",
  "questionsPerPractice": 10,
  "passingScore": 70,
  "examQuestionCounts": [
    60
  ],
  "defaultExamCount": 60,
  "examTimeMinutes": 180,
  "examDomainWeights": {
    "numeros": 0.21666666666666667,
    "geometria": 0.31666666666666665,
    "algebra": 0.3,
    "estadistica": 0.16666666666666666
  },
  "referenceLabel": "Tema",
  "disclaimer": "Herramienta independiente de práctica basada en los temas de Matemáticas de noveno año. Los ejercicios son originales; no son preguntas oficiales del MEP ni anticipan las de una convocatoria.",
  "domains": [
    {
      "id": "numeros",
      "name": "Números"
    },
    {
      "id": "geometria",
      "name": "Geometría"
    },
    {
      "id": "algebra",
      "name": "Relaciones y Álgebra"
    },
    {
      "id": "estadistica",
      "name": "Estadística y Probabilidad"
    }
  ],
  "uiTranslations": {
    "Practice Simulator": "Simulador de práctica",
    "PRACTICE SIMULATOR": "SIMULADOR DE PRÁCTICA",
    "Version:": "Versión:",
    "Dashboard": "Inicio",
    "Study dashboard": "Mi progreso",
    "Build confidence with focused practice and review what needs attention.": "Practica por temas y repasa los ejercicios que necesiten más atención.",
    "Practice Tests": "Prácticas",
    "Start exam": "Iniciar examen",
    "Exam": "Examen",
    "Review Mistakes": "Repasar errores",
    "Review mistakes": "Repasar errores",
    "Bookmarks": "Marcadores",
    "Settings": "Configuración",
    "Light theme": "Tema claro",
    "Dark theme": "Tema oscuro",
    "Questions answered": "Preguntas respondidas",
    "Correct answers": "Respuestas correctas",
    "Accuracy": "Porcentaje de aciertos",
    "Best exam score": "Mejor nota de examen",
    "Best score:": "Mejor nota:",
    "Domain performance": "Rendimiento por área",
    "completed": "completadas",
    "Best average:": "Promedio de mejores notas:",
    "bookmarked questions": "preguntas guardadas",
    "bookmarked question": "pregunta guardada",
    "Continue Practice": "Continuar prácticas",
    "Open bookmarks": "Abrir marcadores",
    "Recommended next ·": "Recomendada ·",
    "Practice Test": "Práctica",
    "Fixed question set": "Grupo fijo de preguntas",
    "Completed": "Completada",
    "Mastered": "Dominada",
    "Not completed": "Sin completar",
    "Latest:": "Última nota:",
    "Best:": "Mejor nota:",
    "Attempts:": "Intentos:",
    "Retake Test": "Repetir práctica",
    "Start Test": "Iniciar práctica",
    "Practice Progress": "Progreso de prácticas",
    "of": "de",
    "tests completed": "prácticas completadas",
    "questions completed through practice tests": "preguntas completadas en prácticas",
    "Overall progress": "Progreso total",
    "Average latest score:": "Promedio de últimas notas:",
    "Average best score:": "Promedio de mejores notas:",
    "Exam setup": "Configuración del examen",
    "Practice setup": "Configuración de práctica",
    "Number of questions": "Cantidad de preguntas",
    "All available": "Todas las disponibles",
    "All domains": "Todas las áreas",
    "Domain": "Área",
    "Difficulty": "Dificultad",
    "All difficulties": "Todas las dificultades",
    "easy": "Fácil",
    "medium": "Intermedia",
    "hard": "Mayor dificultad",
    "Question selection": "Selección de preguntas",
    "Random": "Aleatoria",
    "Unanswered": "Sin responder",
    "Previously incorrect": "Con errores anteriores",
    "Bookmarked": "Guardada",
    "Timer": "Tiempo",
    "On": "Activado",
    "Off": "Desactivado",
    "minutes": "minutos",
    "Randomize answers": "Mezclar opciones",
    "Start practice": "Iniciar práctica",
    "Cancel": "Cancelar",
    "Exam Simulator": "Simulacro de examen",
    "Question": "Pregunta",
    "question": "pregunta",
    "questions": "preguntas",
    "remaining": "restantes",
    "answered": "respondido",
    "Bookmark": "Guardar",
    "Choose": "Elige",
    "answers": "respuestas",
    "Previous": "Anterior",
    "Marked": "Marcada",
    "Mark for review": "Marcar para repasar",
    "Check answer": "Revisar respuesta",
    "End exam": "Terminar examen",
    "Finish Practice": "Finalizar práctica",
    "Next": "Siguiente",
    "Question navigator": "Navegador de preguntas",
    "Correct answer:": "Respuesta correcta:",
    "Explanation": "Procedimiento",
    "Key clue": "Pista clave",
    "Why the options are correct or incorrect": "Por qué cada opción es correcta o incorrecta",
    "Mental model": "Guía para recordar",
    "Exam tip:": "Consejo para el examen:",
    "Try again": "Intentar de nuevo",
    "Correct": "Correcta",
    "Incorrect": "Incorrecta",
    "No detailed explanation available for this option.": "No hay una explicación detallada para esta opción.",
    "No detailed explanation available for this question.": "No hay una explicación detallada para esta pregunta.",
    "Select the required answer(s)": "Selecciona la respuesta requerida",
    "Choose exactly": "Selecciona exactamente",
    "answer": "respuesta",
    "before checking.": "antes de revisar.",
    "Submit exam?": "¿Entregar el examen?",
    "You still have": "Todavía hay",
    "unanswered question": "pregunta sin responder",
    "unanswered questions": "preguntas sin responder",
    "marked for review.": "marcadas para repasar.",
    "Return to exam": "Volver al examen",
    "Submit anyway": "Entregar",
    "Answer required": "Falta una respuesta",
    "Select the required answer(s) before finishing this practice test.": "Selecciona la respuesta requerida antes de finalizar esta práctica.",
    "Exam results": "Resultados del examen",
    "Local simulator score": "Nota de este simulador",
    "PASS": "APROBADO",
    "NEEDS REVIEW": "REQUIERE REPASO",
    "This simulator percentage is a local practice score and may not match an external examination’s scoring method.": "Esta nota corresponde a la práctica y no sustituye la calificación de una evaluación oficial.",
    "Summary": "Resumen",
    "Correct:": "Correctas:",
    "Incorrect:": "Incorrectas:",
    "Total:": "Total:",
    "Time used:": "Tiempo utilizado:",
    "Domain breakdown": "Resultados por área",
    "Topic breakdown": "Resultados por tema",
    "Review all questions": "Repasar todas las preguntas",
    "Review incorrect questions": "Repasar preguntas incorrectas",
    "Review marked questions": "Repasar preguntas marcadas",
    "Bookmarked questions": "Preguntas guardadas",
    "available.": "disponibles.",
    "Practice these questions": "Practicar estas preguntas",
    "No": "No",
    "incorrect": "incorrectas",
    "bookmarked": "guardadas",
    "questions yet.": "preguntas todavía.",
    "Show exam tips": "Mostrar consejos",
    "Keyboard shortcuts": "Atajos de teclado",
    "Default practice count": "Preguntas de práctica por defecto",
    "Save settings": "Guardar configuración",
    "Reset statistics only": "Restablecer solo estadísticas",
    "Reset study progress": "Restablecer progreso",
    "Shortcuts: 1–4 choose an option, ←/→ navigate, M marks for review.": "Atajos: 1–4 eligen una opción, ←/→ cambian de pregunta y M marca para repasar.",
    "Question review": "Repaso de preguntas",
    "Your answer:": "Tu respuesta:",
    "Not answered": "Sin respuesta",
    "No questions match this review.": "No hay preguntas para este repaso.",
    "Back to results": "Volver a resultados",
    "Complete": "Completada",
    "Score": "Nota",
    "Review Incorrect Answers": "Repasar respuestas incorrectas",
    "Back to Practice Tests": "Volver a prácticas",
    "Close": "Cerrar",
    "No matching questions": "No hay preguntas coincidentes",
    "Change your filters or answer more questions first.": "Cambia los filtros o responde otras preguntas primero.",
    "Skip to content": "Ir al contenido",
    "Delete all study progress, bookmarks, and settings?": "¿Eliminar el progreso, los marcadores y la configuración de este curso?",
    "Reset answers, statistics, and exam history?": "¿Restablecer las respuestas, las estadísticas y el historial de exámenes de este curso?",
    "All Courses": "Todos los cursos",
    "Appearance": "Apariencia",
    "Theme": "Tema",
    "Dark": "Oscuro",
    "Light": "Claro",
    "Study preferences": "Preferencias de estudio",
    "Data": "Datos"
  }
};
